config/routes.rb
Rails.application.routes.draw do

  # プロフィール編集をパスワード無しにする
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root "homes#top"

  resources :users, only: [:index, :show, :create] do
    resource :relationships, only: [:create, :destroy]
    get :following, :followers
  end

  resources :books do
    resources :comments, only: [:create, :destroy, :update]
    resource :likes, only: [:create, :destroy]
  end

  get "/search", to: "books#search"

  resources :categories, only: [:index, :create, :show]

  resources :chats, only: [:create]
  get "chat/:id" => "chats#show", as: "chat"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :image
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy

  validates :name, presence: true, length: {maximum: 30}
  validates :email, uniqueness: true, length: {maximum: 50}
  validates :introduction, presence: true, length: {maximum: 200}

  def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.create(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def after_update_path_for(resource)
    user_path(@user)
  end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :introduction, :image])
    flash[:notice] = "プロフィールを変更しました。"
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.order(id: :desc).page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.order(id: :desc).page(params[:page]).per(15)
    @follower = Relationship.where(follow_id: @user.id)
  end

  def following
    @user = User.find(params[:user_id])
    following_id = @user.relationships.order(id: :desc).pluck(:follow_id)
    @following_users = []
    following_id.each do |f|
      @following_users.append(User.find(f))
    end
    @followers = Relationship.where(follow_id: @user.id)
  end

  def followers
    @user = User.find(params[:user_id])
    followers_id = Relationship.where(follow_id: @user.id).order(id: :desc).pluck(:user_id)
    @followers = []
    followers_id.each do |f|
      @followers.append(User.find(f))
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<% breadcrumb :followers, @user %>
<br>
<div class="jumbotron">
    <h1 class="display-4"><%= @user.name %> のフォロワー一覧</h1>
  <%= attachment_image_tag @user, :image, size: "300x300", style: "border-radius: 50%;", fallback: "no_image.jpeg" %>
  <div class="d-flex justify-content-end">
    <p class="m-3"><%= render "relationships/follow", user: @user %></p>&emsp;
    <%= link_to user_following_path(@user) do %>
      <h5 class="m-3">フォロー <%= @user.relationships.count %></h5>
    <% end %>
    <%= link_to user_followers_path(@user) do %>
      <h5 class="m-3">フォロワー <%= @followers.count %></h5>
    <% end %>
  </div>
  <hr class="my-4">
  <h5><%= @user.introduction %></h5><br>
  <% if current_user.id == @user.id %>
    <%= link_to edit_user_registration_path(current_user), class: "btn btn-success" do %>
      プロフィール編集
    <% end %>
  <% end %>
</div>

<% @followers.each do |follower| %>
  <div class="card col-8 mx-auto">
    <div class="card-body">
      <div class="d-flex">
        <div class="col-3 text-center">
          <%= link_to user_path(follower), class: "link text-dark" do %>
            <%= attachment_image_tag follower, :image, size: "100x100", style: "border-radius: 50%;", fallback: "no_image.jpeg" %>
            <br><br>
            <h5><%= follower.name %></h5>
          <% end %>
        </div>
        <div class="col-9">
          <div><%= follower.introduction %></div>
        </div>
      </div>
      <div class="d-flex align-items-end justify-content-end">
        <%= link_to user_following_path(follower) do %>
          <p>フォロー<%= follower.followings.count %></p>
        <% end %>
        &emsp;
        <%= link_to user_followers_path(follower) do %>
          <p>フォロワー<%= follower.followers.count %></p>
        <% end %>
      </div>
    </div>
  </div>
  <br>
<% end %>

app/views/users/following.html.erb
<% breadcrumb :following, @user %>
<br>
<div class="jumbotron">
    <h1 class="display-4"><%= @user.name %> のフォロー一覧</h1>
  <%= attachment_image_tag @user, :image, size: "300x300", style: "border-radius: 50%;", fallback: "no_image.jpeg" %>
  <div class="d-flex justify-content-end">
    <p class="m-3"><%= render "relationships/follow", user: @user %></p>&emsp;
    <%= link_to user_following_path(@user) do %>
      <h5 class="m-3">フォロー <%= @user.relationships.count %></h5>
    <% end %>
    <%= link_to user_followers_path(@user) do %>
      <h5 class="m-3">フォロワー <%= @followers.count %></h5>
    <% end %>
  </div>
  <hr class="my-4">
  <h5><%= @user.introduction %></h5><br>
  <% if current_user.id == @user.id %>
    <%= link_to edit_user_registration_path(current_user), class: "btn btn-success" do %>
      プロフィール編集
    <% end %>
  <% end %>
</div>

<% @following_users.each do |user| %>
  <div class="card col-8 mx-auto">
    <div class="card-body">
      <div class="d-flex">
        <div class="col-3 text-center">
        <%= link_to user_path(user), class: "link text-dark" do %>
        <br>
            <%= attachment_image_tag user, :image, size: "100x100", style: "border-radius: 50%;", fallback: "no_image.jpeg" %>
            <br><br>
            <%= user.name %>
          </div>
        <% end %>
        <div class="col-9">
          <div><%= user.introduction %></div>
        </div>
      </div>
      <div class="d-flex align-items-end justify-content-end">
        <%= link_to user_following_path(user) do %>
          <p>フォロー<%= user.followings.count %></p>
        <% end %>
        &emsp;
        <%= link_to user_followers_path(user) do %>
          <p>フォロワー<%= user.followers.count %></p>
        <% end %>
      </div>
    </div>
  </div>
  <br>
<% end %>

app/views/users/index.html.erb
<% breadcrumb :user_index %>
<br>
<div class="jumbotron">
  <h1 class="display-4">ユーザー一覧</h1>
  <p class="lead">気になる人をフォローしよう</p>
  <hr class="my-4">
  <p>共有された参考書を調べて自分の力に！<br>
</div>
<div class="card-deck">
  <% @users.each do |user| %>
    <div class="col-4">
      <br>
      <%= link_to user_path(user), id: "users#{user.id}", class: "link text-dark", style: "z-index: -2;" do %>
        <div class="card">
          <%= attachment_image_tag user, :image, size: "318x300", class: "rounded", fallback: "no_image.jpeg" %>
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <h5 class="card-name"><%= user.name %></h5>
              <% if current_user.following?(user) %>
                <h5 class="text-primary">フォロー中</h5>
              <% end %>
            </div>
            <br>
            <span>フォロー <%= user.followings.count %></span>
            <span>フォロワー <%= user.followers.count %></span>
            <br><br>
            <p><%= user.introduction %></p>
            <hr>
            <h5>投稿書籍</h5>
            <% user.books.limit(3).each do |book| %>
              <p class="card-books"><%= book.title %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<br>
<div class="d-flex justify-content-center">
  <%= paginate @users %>
</div>

app/views/users/show.html.erb
<% breadcrumb :user_show, @user %>
<br>
<div class="jumbotron">
  <% if current_user == @user %>
    <h1 class="display-4">マイページ</h1>
  <% else %>
    <h1 class="display-4"><%= @user.name %>のページ</h1>
  <% end %>
  <%= attachment_image_tag @user, :image, size: "300x300", style: "border-radius: 50%;", fallback: "no_image.jpeg" %>
  <div class="d-flex justify-content-end">
    <% unless current_user == @user %>
      <p class="m-3"><%= link_to "チャット", chat_path(@user.id), class: "btn btn-secondary" %></p>
    <% end %>
    <p class="m-3"><%= render "relationships/follow", user: @user %></p>&emsp;
    <%= link_to user_following_path(@user) do %>
      <h5 class="m-3">フォロー <%= @user.relationships.count %></h5>
    <% end %>
    <%= link_to user_followers_path(@user) do %>
      <h5 class="m-3">フォロワー <%= @follower.count %></h5>
    <% end %>
  </div>
  <hr class="my-4">
  <h4><%= @user.name %></h4>
  <h5><%= @user.introduction %></h5><br>
  <% if current_user.id == @user.id %>
    <%= link_to edit_user_registration_path(current_user), class: "btn btn-success" do %>
      プロフィール編集
    <% end %>
  <% end %>
</div>

<div class="card-deck">
  <% @books.each do |book| %>
    <div class="col-4">
      <br>
      <%= link_to book_path(book), class: "link text-dark" do %>
        <div class="card">
          <%= attachment_image_tag book, :image, size: "318x300", class: "rounded", fallback: "no_image.jpeg" %>
          <div class="card-body">
            <h5 class="card-title"><%= book.title %></h5>
            <p class="card-author"><%= book.author %></p>
            <hr>
            <p class="card-text"><%= book.body.truncate(30) %></p>
            <p class="card-text"><small class="text-muted"><%= book.created_at.strftime("%Y-%m-%d　%H:%M") %></small></p>
            <% if book.user_id == current_user.id %>
              <%= link_to "編集", edit_book_path(book) %>
              <%= link_to "削除", book_path(book), method: :delete, data: {confirm: "本当に削除しますか？"} %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<br>
<div class="d-flex justify-content-center">
  <%= paginate @books %>
</div>