config/routes.rb
Rails.application.routes.draw do

  # プロフィール編集をパスワード無しにする
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root "homes#top"

  resources :users, only: [:index, :show, :create] do
    resource :relationships, only: [:create, :destroy]
    get :following, :followers
  end

  resources :books do
    resources :comments, only: [:create, :destroy, :update]
    resource :likes, only: [:create, :destroy]
  end

  get "/search", to: "books#search"

  resources :categories, only: [:index, :create, :show]

  resources :chats, only: [:create]
  get "chat/:id" => "chats#show", as: "chat"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user
    belongs_to :category
    attachment :image
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy

    def liked_by?(user)
        likes.where(user_id: user.id).exists?
    end

    validates :title, presence: true, length: {maximum: 30}
    validates :author, presence: true, length: {maximum: 30}
    validates :body, presence: true
    validates :image, presence: true

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :message, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :image
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy

  validates :name, presence: true, length: {maximum: 30}
  validates :email, uniqueness: true, length: {maximum: 50}
  validates :introduction, presence: true, length: {maximum: 200}

  def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.create(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.includes(:user, :category).order(id: :desc).page(params[:page]).per(15)
  end

  def show
    @book = Book.find(params[:id])
    @comments = @book.comments.includes(:user).order(id: :desc)
    @comment = Comment.new
    @user = @book.user
  end

  def new
    @book = Book.new
    @categories = Category.preload(:user).order(:name)
  end

  def create
    if params[:book][:category_id] == ""
      params[:book][:category_id] = Category.find_or_create_by(name: params[:book][:name]).id
    end
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "投稿しました。"
      redirect_to books_path
    else
      @categories = Category.preload(:user).order(:name)
      render :new
    end
  end

  def update
    if params[:book][:category_id] == ""
      params[:book][:category_id] = Category.find_or_create_by(name: params[:book][:name]).id
    end
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path, notice: "編集を登録しました。"
    else
      @categories = Category.preload(:user).order(:name)
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_back(fallback_location: root_path)
    flash[:notice] = "投稿を削除しました。"
  end

  def search
    @keyword = params[:keyword]
    if @keyword == ""
      redirect_to books_path
    end
    @books = Book.where('title LIKE(?) OR author LIKE(?)', "%#{@keyword}%","%#{@keyword}%").includes(:user, :category).page(params[:page]).per(15)
  end

  private

  def book_params
    params.require(:book).permit(:user_id, :category_id, :title, :author, :body, :image)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end

    @chats = @room.chats.includes(:user).order(id: :desc)
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    rooms = current_user.user_rooms.pluck(:room_id)
    @chats = UserRoom.find_by(room_id: params[:chat][:room_id]).room.chats.includes(:user).order(id: :desc)
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @like = current_user.likes.new(book_id: @book.id)
    @like.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    like = current_user.likes.find_by(book_id: @book.id)
    like.destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.order(id: :desc).page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.order(id: :desc).page(params[:page]).per(15)
    @follower = Relationship.where(follow_id: @user.id)
  end

  def following
    @user = User.find(params[:user_id])
    following_id = @user.relationships.order(id: :desc).pluck(:follow_id)
    @following_users = []
    following_id.each do |f|
      @following_users.append(User.find(f))
    end
    @followers = Relationship.where(follow_id: @user.id)
  end

  def followers
    @user = User.find(params[:user_id])
    followers_id = Relationship.where(follow_id: @user.id).order(id: :desc).pluck(:user_id)
    @followers = []
    followers_id.each do |f|
      @followers.append(User.find(f))
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_search_form.html.erb
<%= form_tag('/search', method: :get) do %>
  <div class="form-inline mt-1">
    <input class="form-control w-75" name="keyword", placeholder="何をお探しですか？", type="text", value="">
    <button class="btn btn-info w-25" title: "検索", type: "submit">検索</button>
  </div>
<% end %>

app/views/books/edit.html.erb
<br>
<div class="jumbotron">
  <h1><%= @book.title %>の編集</h1>
  <p class="lead">より良い情報を伝えてあげよう</p>
  <hr class="my-4">
  <p>共有された参考書を調べて自分の力に！<br></p>
  <!--<a class="btn btn-primary btn-lg" href="/users/sign_up" role="button">新規登録</a>-->
</div>
<br>
<%= form_with model: @book, local: true do |f| %>
  <%= render "layouts/error_messages", model: f.object %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <table class="table table-borderless col-8 mx-auto">

    <tr>
      <th>
        画像
      </th>
      <td>
        <%= f.attachment_field :image %>
      </td>

    </tr>
    <tr>
      <th>
        <%= f.label :タイトル %>
      </th>
      <td>
        <%= f.text_field :title, class: "form-control" %>
      </td>
    </tr>

    <tr>
      <th>
        <%= f.label :著者 %>
      </th>
      <td>
        <%= f.text_field :author, class: "form-control" %>
      </td>
    </tr>

    <tr>
      <th>
        <%= f.label :カテゴリ %>
      </th>
      <td>
        <%= f.select :category_id, @categories.pluck(:name, :id),{include_blank: "カテゴリを選択してください。"}, class: "form-control" %>
      </td>
    </tr>

    <tr>
      <th>
        <%= f.label :カテゴリ（その他） %>
      </th>
      <td>
        <%= f.text_field :name, class: "form-control" %>
      </td>
    </tr>

    <tr>
      <th>
        <%= f.label :説明 %>
      </th>
      <td>
        <%= f.text_field :body, class: "form-control" %>
      </td>
    </tr>
  </table>

  <div class="actions text-center">
    <%= f.submit "登録", class: "btn btn-primary" %><br>
  </div>
<% end %>
<br>

app/views/books/index.html.erb
<% breadcrumb :book_index %>
<br>
<div class="jumbotron">
  <h1 class="display-4">ようこそ <%= current_user.name %> さん！</h1>
  <p class="lead">おすすめの参考書を紹介して共有しよう</p>
  <hr class="my-4">
  <p>共有された参考書を調べて自分の力に！<br></p>
</div>

<% unless @books.exists? %>
  <h4>検索結果はありません</h4>
<% else %>
<div class="card-deck">
  <% @books.each do |book| %>
    <div class="col-4">
      <br>
      <%= link_to book_path(book), class: "link text-dark", id: "books#{book.id}" do %>
        <div class="card">
          <%= attachment_image_tag book, :image, size: "318x300", class: "rounded" %>
          <div class="card-body">
            <h5 class="card-title"><%= book.title %></h5>
            <p class="card-author"><%= book.author %></p>
            <span>カテゴリ：</span>
            <span><%= book.category.name %></span>
            <br><br>
            <div class="d-flex justify-content-between">
              <p>コメント <%= book.comments.count %></p>
              <p>❤︎ <%= book.likes.count %></p>
            </div>
            <hr>
            <p class="card-user">投稿者：<%= book.user.name %></p>
            <p class="card-text"><%= book.body.truncate(30) %></p>
            <p class="card-text"><small class="text-muted"><%= book.created_at.strftime("%Y-%m-%d　%H:%M") %></small></p>
            <% if book.user_id == current_user.id %>
              <%= link_to "編集", edit_book_path(book) %>
              <%= link_to "削除", book_path(book), method: :delete, data: {confirm: "本当に削除しますか？"} %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<% end %>
<br>
<div class="d-flex justify-content-center">
  <%= paginate @books %>
</div>

app/views/books/new.html.erb
<% breadcrumb :book_new %>
<br>
<div class="jumbotron">
  <h1 class="display-4">投稿フォーム</h1>
  <p class="lead">おすすめの参考書を紹介して共有しよう</p>
  <hr class="my-4">
  <p>共有された参考書を調べて自分の力に！<br>
</div>
<br>
<%= form_with model: @book do |f| %>
  <%= render "layouts/error_messages", model: f.object %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <table class="table table-borderless col-8 mx-auto">

    <tr>
      <th>
        <%= f.label :画像 %>
      </th>
      <td>
        <%= f.attachment_field :image %>
      </td>
    </tr>

    <tr>
      <th>
        <%= f.label :タイトル %>
      </th>
      <td>
        <%= f.text_field :title, class: "form-control" %>
      </td>
    </tr>

    <tr>
      <th>
        <%= f.label :著者 %>
      </th>
      <td>
        <%= f.text_field :author, class: "form-control" %>
      </td>
    </tr>

    <tr>
      <th>
        <%= f.label :カテゴリ %>
      </th>
      <td>
        <%= f.select :category_id, @categories.pluck(:name, :id),{include_blank: "カテゴリを選択してください。"}, class: "form-control" %>
      </td>
    </tr>

    <tr>
      <th>
        <%= f.label :カテゴリ（その他） %>
      </th>
      <td>
        <%= f.text_field :name, class: "form-control" %>
      </td>
    </tr>

    <tr>
      <th>
        <%= f.label :説明 %>
      </th>
      <td>
        <%= f.text_area :body, class: "form-control" %>
      </td>
    </tr>
  </table>

  <div class="actions text-center">
    <%= f.submit "登録", class: "btn btn-primary" %><br>
  </div>
<% end %>
<br>

app/views/books/search.html.erb
<% breadcrumb :book_search %>
<br>
<div class="jumbotron">
  <h1 class="display-4"><%= params[:keyword] %> の検索結果</h1>
  <p class="lead">おすすめの参考書を紹介して共有しよう</p>
  <hr class="my-4">
  <p>共有された参考書を調べて自分の力に！<br></p>
</div>

<% unless @books.exists? %>
  <h4>検索結果はありません</h4>
<% else %>
<div class="card-deck">
  <% @books.each do |book| %>
    <div class="col-4">
      <br>
      <%= link_to book_path(book), class: "link text-dark" do %>
        <div class="card">
          <%= attachment_image_tag book, :image, size: "318x300", class: "rounded" %>
          <div class="card-body">
            <h5 class="card-title"><%= book.title %></h5>
            <p class="card-author"><%= book.author %></p>
            <span>カテゴリ：</span>
            <span><%= book.category.name %></span>
            <br><br>
            <div class="d-flex justify-content-between">
              <p>コメント <%= book.comments.count %></p>
              <p>❤︎ <%= book.likes.count %></p>
            </div>
            <hr>
            <p class="card-user">投稿者：<%= book.user.name %></p>
            <p class="card-text"><%= book.body.truncate(30) %></p>
            <p class="card-text"><small class="text-muted"><%= book.created_at.strftime("%Y-%m-%d　%H:%M") %></small></p>
            <% if book.user_id == current_user.id %>
              <%= link_to "編集", edit_book_path(book) %>
              <%= link_to "削除", book_path(book), method: :delete, data: {confirm: "本当に削除しますか？"} %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<% end %>
<br>
<div class="d-flex justify-content-center">
  <%= paginate @books %>
</div>

app/views/books/show.html.erb
<% breadcrumb :book_show, @book %>
<br>
<div class="jumbotron">
  <h1 class="display-4">投稿詳細</h1>
  <p class="lead"></p>
  <hr class="my-4">
  <p>共有された参考書を調べて自分の力に！<br>
</div>
<br>
<div class="card-deck">
  <div class="col-8 mx-auto">
    <div class="card">
      <%= attachment_image_tag @book, :image, size: "698x500" %>
      <div class="card-body">
        <h5 class="card-title"><%= @book.title %></h5>
        <p class="card-author"><%= @book.author %></p>
        <div class="d-flex justify-content-between">
          <span>カテゴリ：<%= @book.category.name %></span>
          <span id="like"><%= render "likes/like", book: @book, like: @like %></span>
        </div>
        <hr>
        <%= link_to user_path(@book.user), class: "link text-dark" do %>
          <p>投稿者：<%= @book.user.name %></p>
        <% end %>
        <p class="card-text"><%= @book.body %></p>
        <p class="card-text"><small class="text-muted"><%= @book.created_at.strftime("%Y-%m-%d　%H:%M") %></small></p>
        <% if @book.user_id == current_user.id %>
          <%= link_to "編集", edit_book_path(@book) %>
          <%= link_to "削除", book_path(@book), method: :delete, data: {confirm: "本当に削除しますか？"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>


<%= render "comments/comment_form", comment: @comment, book: @book %>
<%= render "comments/comment", comments: @comments, book: @book, user: @user %>

app/views/chats/_chat.html.erb
<div class="overflow-auto col-8 mx-auto", style="height: 50rem; background-color: #87cefa;">
  <% chats.each do |chat| %>
    <div class="talk">
      <% unless current_user.id == chat.user_id %>
        <div class="talk_left">
        <%= link_to user_path(chat.user_id), class: "link text-dark" do %>
          <%= attachment_image_tag chat.user, :image, size: "40x40", style: "border-radius: 50%;", fallback: "no_image.jpeg" %>
        <% end %>
          <p><%= chat.message %></p>
          <span style="font-size: 5px;"><%= chat.created_at.strftime("%m-%d　%H:%M") %></span>
        </div>
      <% else %>
        <div class="talk_right d-flex">
          <span class="mt-4 mr-1", style="font-size: 5px;"><%= chat.created_at.strftime("%m-%d　%H:%M") %></span>
          <p><%= chat.message %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/chats/create.js.erb
$('.chats').html('<%= j(render "chat", chats: @chats) %>');
$('textarea').val('');
if ($('#chat_error') != "") {

<% if params[:chat][:message] == "" %>
$('#chat_error').html("内容を入力してください")
$(function(){
	setTimeout(function(){
		$('#chat_error').html('')
	},4000);
});
<% end %>
}

app/views/chats/show.html.erb
<% breadcrumb :chat, @user %>
<br>
<div class="jumbotron">
  <h1 class="display-4"><%= @user.name %> さんとのチャット</h1>
  <p class="lead">交流して知識を増やそう</p>
  <hr class="my-4">
  <p>共有された参考書を調べて自分の力に！<br></p>
</div>

<div class="row">
  <div class="col-6 mx-auto">
    <div id='chat_error'></div>
    <%= form_with model: @chat, local: false do |f| %>
      <%= f.hidden_field :room_id %>
      <%= f.label :チャット %>
      <div class="d-flex">
        <%= f.text_area :message, class: "form-control", style: "resize: none;" %>
        <%= f.submit "投稿", class: "btn btn-primary m-3", id: "submit" %>
      </div>
    <% end %>
  </div>
</div>
<br><br>
<div class="chats">
  <%= render "chat", chats: @chats %>
</div>
<br>

app/views/likes/_like.html.erb
<% if book.liked_by?(current_user) %>
  <span>
    <%= link_to book_likes_path(book), method: :delete, remote: true do %>
      ♥<%= book.likes.count %> いいね
    <% end %>
  </span>
  <% else %>
  <span>
    <%= link_to book_likes_path(book), method: :post, remote: true do %>
      ♡<%= book.likes.count %> いいね
    <% end %>
  </span>
<% end %>

app/views/likes/create.js.erb
$('#like').html("<%= j(render 'likes/like', book: @book, like: @like) %>");

app/views/likes/destroy.js.erb
$('#like').html("<%= j(render 'likes/like', book: @book, like: @like) %>");