config/routes.rb
Rails.application.routes.draw do

  # プロフィール編集をパスワード無しにする
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  root "homes#top"

  resources :users, only: [:index, :show, :create] do
    resource :relationships, only: [:create, :destroy]
    get :following, :followers
  end

  resources :books do
    resources :comments, only: [:create, :destroy, :update]
    resource :likes, only: [:create, :destroy]
  end

  get "/search", to: "books#search"

  resources :categories, only: [:index, :create, :show]

  resources :chats, only: [:create]
  get "chat/:id" => "chats#show", as: "chat"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user
    belongs_to :category
    attachment :image
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy

    def liked_by?(user)
        likes.where(user_id: user.id).exists?
    end

    validates :title, presence: true, length: {maximum: 30}
    validates :author, presence: true, length: {maximum: 30}
    validates :body, presence: true
    validates :image, presence: true

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :message, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :image
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy

  validates :name, presence: true, length: {maximum: 30}
  validates :email, uniqueness: true, length: {maximum: 50}
  validates :introduction, presence: true, length: {maximum: 200}

  def update_without_current_password(params, *options)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.create(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.includes(:user, :category).order(id: :desc).page(params[:page]).per(15)
  end

  def show
    @book = Book.find(params[:id])
    @comments = @book.comments.includes(:user).order(id: :desc)
    @comment = Comment.new
    @user = @book.user
  end

  def new
    @book = Book.new
    @categories = Category.preload(:user).order(:name)
  end

  def create
    if params[:book][:category_id] == ""
      params[:book][:category_id] = Category.find_or_create_by(name: params[:book][:name]).id
    end
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "投稿しました。"
      redirect_to books_path
    else
      @categories = Category.preload(:user).order(:name)
      render :new
    end
  end

  def update
    if params[:book][:category_id] == ""
      params[:book][:category_id] = Category.find_or_create_by(name: params[:book][:name]).id
    end
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path, notice: "編集を登録しました。"
    else
      @categories = Category.preload(:user).order(:name)
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_back(fallback_location: root_path)
    flash[:notice] = "投稿を削除しました。"
  end

  def search
    @keyword = params[:keyword]
    if @keyword == ""
      redirect_to books_path
    end
    @books = Book.where('title LIKE(?) OR author LIKE(?)', "%#{@keyword}%","%#{@keyword}%").includes(:user, :category).page(params[:page]).per(15)
  end

  private

  def book_params
    params.require(:book).permit(:user_id, :category_id, :title, :author, :body, :image)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end

    @chats = @room.chats.includes(:user).order(id: :desc)
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    rooms = current_user.user_rooms.pluck(:room_id)
    @chats = UserRoom.find_by(room_id: params[:chat][:room_id]).room.chats.includes(:user).order(id: :desc)
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= key %> w-75 mx-auto">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-lg-start">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <% if user_signed_in? %>

      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">ユーザーページ</h5>

        <ul class="list-unstyled mb-0">
          <li>
            <%= link_to user_path(current_user) do %>
              <p class="text-dark">マイページ</p>
            <% end %>
          </li>
          <li>
            <%= link_to users_path do%>
              <p class="text-dark">ユーザー一覧</p>
            <% end %>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">書籍ページ</h5>

        <ul class="list-unstyled">
          <li>
            <%= link_to books_path do %>
              <p class="text-dark">書籍一覧</p>
            <% end %>
          </li>
          <li>
            <a href="/categories" class="text-dark" >カテゴリ</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">投稿ページ</h5>

        <ul class="list-unstyled mb-0">
          <li>
            <a href="/books/new" class="text-dark">新規投稿</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">ログイン状態</h5>

        <ul class="list-unstyled">
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <p class="text-dark">サインアウト</p>
            <% end %>
          </li>
        </ul>
      </div>
      <!--Grid column-->
      <% else %>
      <div class="col mx-auto">
        <ul class="list-unstyled mb-0">
          <li>
            <%= link_to new_user_registration_path do %>
              <p class="text-dark">新規登録</p>
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to new_user_session_path do %>
              <p class="text-dark">ログイン</p>
            <% end %>
          </li>
        </ul>
      </div>
      <% end %>
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Reference Book BLOG
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="/">Reference book BLOG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to user_path(current_user), id: "mypage" do %>
            <p class="nav-link">マイページ</p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_book_path, id: "book_new" do %>
            <p class="nav-link">新規投稿</p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_path, id: "users" do %>
            <p class="nav-link">ユーザー一覧</p>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            書籍
          </a>
          <div class="dropdown-menu text-center" aria-labelledby="navbarDropdownMenuLink">
            <a href="/books" class="dropdown-item" id="book_index">一覧</a>
            <a href="/categories" class="dropdown-item" id="category_index">カテゴリ</a>
          </div>
        </li>
        <li class="nav-item active">
          <%= link_to destroy_user_session_path, method: :delete, id: "signout" do %>
            <p class="nav-link">サインアウト</p>
          <% end %>
        </li>
        <% if params[:controller] == "books" %>
          <li class="nav-item" id="search_form">
            <%= render "search_form" %>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item active">
          <%= link_to new_user_registration_path do %>
            <p class="nav-link">新規登録</p>
          <% end %>
        </li>
        <li class="nav-item active">
          <%= link_to new_user_session_path, id: "login" do %>
            <p class="nav-link">ログイン</p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%#= breadcrumbs separator: " &rsaquo; " %>
      <%= breadcrumbs separator: " > " %>
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
      <%= render "layouts/footer" %>
  </body>
</html>